sudo: required
services:
  - docker

before_install:
  - docker build -t casperak/react-test -f ./client/Dockerfile.dev .

script:
  - docker run casperak/react-test npm test -- --coverage

after_success:
  - docker build -t casperak/multi-client ./client
  - docker build -t casperak/multi-nginx ./nginx
  - docker build -t casperak/multi-server ./server
  - docker build -t casperak/multi-worker ./worker
  # Login to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push casperak/multi-client
  - docker push casperak/multi-nginx
  - docker push casperak/multi-server
  - docker push casperak/multi-worker

